export const jsonkeys = {
  population: "populationModel.value",
  buildingCount: "buildingFootprintModel.buildingCount",
  buildingAreaCoverage: "buildingFootprintModel.buildingAreaCoverage",
  averageBuildingHeight: "buildingHeightModel.averageBuildingHeight",
  building3lessAreaCoverage: "buildingHeightModel.building3lessAreaCoverage",
  building3to8AreaCoverage: "buildingHeightModel.building3to8AreaCoverage",
  building8moreAreaCoverage: "buildingHeightModel.building8moreAreaCoverage",
  getObjs: "objectDetectionModel",
  landUseModel: "landUseModel",
  economicExposure: "exposureValues.economicExposure",
  insuranceExposure: "exposureValues.insuranceExposure",
  incomePerCapita: "stats.incomePerCapita",
  statPopulation: "stats.population",
  housingUnitsTotal: "stats.housingUnitsTotal",
  averageUnitPrice: "stats.averageUnitPrice",
  medianUnitPrice: "stats.medianUnitPrice",
  unitsInStructure1: "stats.unitsInStructure1",
  unitsInStructure2to9: "stats.unitsInStructure2to9",
  unitsInStructure10to19: "stats.unitsInStructure10to19",
  unitsInStructure20more: "stats.unitsInStructure20more",
  unitsInStructureMobile: "stats.unitsInStructureMobile",
};
