trigger: none

name: $(Date:dd-MM-yyyy_HH-mm)

# variables:
# - group: test-credentials

pool: Syncretis-Ubuntu

resources:
  containers:
    - container: node
      image: node:15

jobs:
  - job: Tests
    timeoutInMinutes: 10
    displayName: perfomance_Ð•est
    workspace:
      clean: all
    container: node
    variables:
      - name: NODE_OPTIONS
        value: --max-old-space-size=8192
    steps:
      - task: Bash@3
        displayName: 'check ip'
        inputs:
          targetType: 'inline'
          script: |
            curl 2ip.ru
            echo "nameserver 8.8.8.8" > /etc/resolv.conf
            curl -k https://exro-demo.syncretis.com
      - task: Bash@3
        displayName: 'install dependency'
        inputs:
          targetType: 'inline'
          script: 'npm install yarn && yarn install'
      - task: Bash@3
        displayName: 'Run tests'
        inputs:
          targetType: 'inline'
          script: |
            yarn jest --testPathPattern tests/performance --setupFiles ./setEnvVars  --setupFiles ./env
      - task: CopyFiles@2
         condition: succeededOrFailed()
         inputs:
           sourceFolder: '$(Build.SourcesDirectory)/reports'
          contents: '**/*'
           targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: Copy Reports
      - task: PublishBuildArtifacts@1
        condition: succeededOrFailed()
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: Reports
        displayName: Publish Reports