trigger: none

name: $(Date:dd-MM-yyyy_HH-mm)

# variables:
# - group: test-credentials

pool: Syncretis-Ubuntu

jobs:
  - job: Tests
    timeoutInMinutes: 10
    displayName: api_Tests
    variables:
      - name: NODE_OPTIONS
        value: --max-old-space-size=8192
    steps:
      - task: Bash@3
        displayName: 'Yarn install'
        inputs:
          targetType: 'inline'
          script: 'npm install -g npm && npm install -g yarn'
      - task: Bash@3
        displayName: 'install dependency'
        inputs:
          targetType: 'inline'
          script: 'yarn install'
      - task: Bash@3
        displayName: 'Run tests'
        inputs:
          targetType: 'inline'
          script: |
            yarn run mocha --require ts-node/register ./tests/**/*.ts