trigger: none

name: $(Date:dd-MM-yyyy_HH-mm)

# variables:
# - group: test-credentials

pool: Syncretis-Ubuntu

resources:
  containers:
    - container: node
      image: alpine:latest
      options: --add-host exro-dev.syncretis.com:51.138.95.195 --entrypoint=""

jobs:
  - job: Tests
    timeoutInMinutes: 10
    displayName: api_Tests
    workspace:
      clean: all
    container: node
    variables:
      - name: NODE_OPTIONS
        value: --max-old-space-size=8192
    steps:
      - task: Bash@3
        displayName: 'install dependency'
        inputs:
          targetType: 'inline'
          script: 'npm install -g yarn && yarn install'
      - task: Bash@3
        displayName: 'Run tests'
        inputs:
          targetType: 'inline'
          script: |
            yarn jest