trigger: none

name: $(Date:dd-MM-yyyy_HH-mm)

# variables:
# - group: test-credentials

pool: Default

resources:
  containers:
    - container: node
      image: node:15

jobs:
  - job: Tests
    timeoutInMinutes: 25
    displayName: Performance_test
    workspace:
      clean: all
    container: node
    variables:
      - name: NODE_OPTIONS
        value: --max-old-space-size=8192
    steps:
      - task: Bash@3
        displayName: create env file
        inputs:
          targetType: 'inline'
          script: |
            echo "token_confluence=$(token_confluence)" > ./.env
            cat ./.env
      - task: Bash@3
        displayName: 'install dependency'
        inputs:
          targetType: 'inline'
          script: 'npm install yarn && yarn install'
      - task: Bash@3
        displayName: 'Run tests'
        inputs:
          targetType: 'inline'
          script: |
            yarn jest --testPathPattern tests/performance --setupFiles ./setEnvVars
      - task: CopyFiles@2
        condition: succeededOrFailed()
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/reports'
          contents: '**/*'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: Copy Reports
      - task: PublishBuildArtifacts@1
        condition: succeededOrFailed()
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: Reports
        displayName: Publish Reports
