trigger:
  - main
pool: Syncretis-Ubuntu

jobs:
  - job: Tests
    timeoutInMinutes: 10
    displayName: api_Tests
    workspace:
      clean: all
    variables:
      - name: NODE_OPTIONS
        value: --max-old-space-size=8192
    steps:
      - task: Bash@3
        displayName: 'Yarn install'
        inputs:
          targetType: 'inline'
          script: 'yarn install'
      - task: Bash@3
        displayName: 'Yarn install'
        inputs:
          targetType: 'inline'
          script: 'printenv'

      - task: Bash@3
        displayName: 'Run tests'
        inputs:
          targetType: 'inline'
          script: |
            yarn run mocha --require ts-node/register ./tests/**/*.ts


