parameters:
  - name: dataValidationForShapes
    type: boolean
  - name: derivativeRights
    type: boolean
  - name: graphql
    type: boolean
  - name: imageService
    type: boolean
  - name: jobExecutions
    type: boolean
  - name: shapeResource
    type: boolean

jobs:
  - job: Tests
    timeoutInMinutes: 15
    displayName: api_Tests
    workspace:
      clean: all
    container: node
    variables:
      - name: NODE_OPTIONS
        value: --max-old-space-size=8192
    steps:
      - task: Bash@3
        displayName: 'install dependency'
        inputs:
          targetType: 'inline'
          script: 'npm install yarn && yarn install'
      - task: Bash@3
        displayName: 'waiting for the end of the deployment'
        inputs:
          targetType: 'inline'
          script: sleep 1m
      - template: template/run-api-test.yml
        parametrs:
          chooseDirTest: ${{ parameters.dataValidationForShapes }}
          yarnScript: 'dataValidationForShapes'
      - template: template/run-api-test.yml
        parametrs:
          chooseDirTest: ${{ parameters.derivativeRights }}
          yarnScript: 'derivativeReghts'
      - template: template/run-api-test.yml
        parametrs:
          chooseDirTest: ${{ parameters.graphql }}
          yarnScript: 'graphql'
      - template: template/run-api-test.yml
        parametrs:
          chooseDirTest: ${{ parameters.imageService }}
          yarnScript: 'imageService'
      - template: template/run-api-test.yml
        parametrs:
          chooseDirTest: ${{ parameters.jobExecutions }}
          yarnScript: 'job-executions'
      - template: template/run-api-test.yml
        parametrs:
          chooseDirTest: ${{ parameters.shapeResource }}
          yarnScript: 'shape-resource'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '$(Build.SourcesDirectory)/reports/*.xml'
          failTaskOnFailedTests: true # Optional
        displayName: Publish test Results to AzureDevops